---
services: docker

env:
  - distro: geerlingguy/docker-centos7-ansible:latest
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: geerlingguy/docker-ubuntu1604-ansible:latest
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: geerlingguy/docker-ubuntu1404-ansible:latest
    init: /sbin/init
    run_opts: ""
  - distro: geerlingguy/docker-ubuntu1204-ansible:latest
    init: /sbin/init
    run_opts: ""
  - distro: ventosus/universal-apple-darwin
    init: ""
    run_opts: ""

before_install:

  # Pull container.
  - 'docker pull ${distro}'
  - sudo apt-get update
  - sudo apt-get install ansible
  - sudo apt-get install -y git curl

script:

  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

  # Install dependencies.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-galaxy install shrikeh.curl'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-galaxy install geerlingguy.git'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role.
  - 'docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'

  # Test role idempotence.
  # - idempotence=$(mktemp)
  # - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
  # - >
  #   tail ${idempotence}
  #   | grep -q 'changed=0.*failed=0'
  #   && (echo 'Idempotence test: pass' && exit 0)
  #   || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/