---

- name: "IVM | Ensure folder requirements are met"
  file:
    path: /usr/local/ivm
    state: directory
    mode: 0777

- name: "IVM | Clone/Update"
  git:
    repo: "{{ ivm_repo }}"
    dest: "{{ fubarhouse_user_dir }}/.ivm"
    clone: yes
    update: yes
    force: yes
    version: master
    recursive: false
  changed_when: false

- name: "IVM | Linking"
  file:
    src: "{{ fubarhouse_user_dir }}/.ivm/bin/ivm"
    dest: "/usr/local/bin/ivm"
    state: link
    force: yes
  changed_when: false

- name: "IVM | Ensure shell profiles are configured"
  lineinfile:
    dest: "{{ fubarhouse_user_dir }}/{{ item.item.item }}"
    regexp: 'export NVM_IOJS_ORG_MIRROR=https://iojs.org/dist'
    line:  'export NVM_IOJS_ORG_MIRROR=https://iojs.org/dist;'
    state: present
  with_items:
    - "{{ available_shell_profiles.results }}"
  when: item.item.stat.exists|bool == true