---

fubarhouse_npm:
  # User
  user: "{{ fubarhouse_user }}"
  user_dir: "/home/{{ fubarhouse_user }}"
  # Shell profiles
  shell_profiles:
    - { filename: .profile }
    - { filename: .bashrc }
    - { filename: .bash_profile }
  # Application versions
  nvm_version: 0.31.0
  # Clean install
  clean_install: false
  # Process controls
  install_nvm: true
  install_ivm: true
  install_nodejs: true
  install_iojs: true
  install_npm: true
  # Repositories
  nvm_repo: "https://github.com/xtuple/nvm.git"
  # Symlinks
  nvm_symlink_exec: "/usr/local/bin/nvm"
  # Install directories
  nvm_install_dir: "/home/{{ fubarhouse_user }}/.nvm"
  folder_paths:
   - { path: "/usr/local/lib/node_modules" }
   - { path: "/home/{{ fubarhouse_user }}/.npm" }
   - { path: "/home/{{ fubarhouse_user }}/.nvm" }
  # Install paths
  nvm_install_path: ""
  # Executables
  nvm_install_exec: "nvm_bin.sh"
  npm_install_exec: "/usr/local/bin/npm"
